name = "sigantara-filemanager-queue-processor"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "sigantara-files"

[[queues.consumers]]
queue = "file-processing-queue"
max_batch_size = 1
max_retries = 3
max_wait_time_ms = 30000

[vars]
DATABASE_URL = ""
R2_PUBLIC_URL = ""
